services:
  mysql:
    image: mysql:8.2
    container_name: dockerized_mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dockerjava
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass

    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
    networks:
      - localnet

  pma:
    depends_on:
      - mysql
    image: phpmyadmin
    container_name: dockerized_pma
    restart: always
    ports:
      - 81:80
    environment:
      - PMA_HOST=mysql
    networks:
      - localnet

  backend:
    depends_on:
      - mysql
    container_name: dockerized_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - .:/dockerized:cached
    ports:
      - "8080:8080"
#    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      DB_HOST: mysql
      DB_USER: appuser
      DB_PASSWORD: apppass
      DB_NAME: dockerjava
    networks:
      - localnet

  frontend:
    depends_on:
      - backend
    container_name: dockerized_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
#    volumes:
#      - .:/dockerized:cached
#    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      VITE_BACKEND_HOST: http://backend:8080
    ports:
      - "80:80"
    networks:
      - localnet

volumes:
  mysql-data:


networks:
  localnet:
    driver: bridge
